#!/bin/bash

#Paraphraser's IOTstack restore script - modified by liamhogan
#UPDATETAG = 20201107-1403

if [ "$#" -ne 1 ]; then
    echo "Usage: restore_iotstack runtag (eg yyyy-mm-dd_hhmm)"
	exit -1
fi

# snapshot the current date and time
RUNTAG=$1

# IOTstack lives here
IOTSTACK="$HOME/IOTstack"

# the backup directory is
RESTOREDIR="$IOTSTACK/restore"
GENERALDIR="$RESTOREDIR/general"

GENERALBACKUP="general-backup.tar.gz"
INFLUXBACKUP="influx-backup.tar"

# create the scaffolding
mkdir -p "$GENERALDIR"

# move into the restore directory
cd "$RESTOREDIR"

# now we can begin
echo "----- Pulling backup images for $RUNTAG from gdrive -----"

rclone copy -P gdrive:/Backups/IOTstack/$RUNTAG.$GENERALBACKUP $RESTOREDIR
rclone copy -P gdrive:/Backups/IOTstack/$RUNTAG.$INFLUXBACKUP $RESTOREDIR

echo "----- Unpacking the general backup -----"

cd "$GENERALDIR"
sudo tar -x --same-owner -z -f ../$GENERALBACKUP

echo "----- Deactivating the stack -----"

cd "$IOTSTACK"
docker-compose down

echo "----- Removing old volumes and services directories -----"

sudo rm -rf ./services ./volumes

echo "----- Moving backup volumes and services into place -----"

sudo mv ./restore/general/services .
sudo mv ./restore/general/volumes .

echo "----- Swapping docker-compose file -----"

sudo mv ./docker-compose.yml ./docker-compose.yml.old
sudo mv ./restore/general/docker-compose.yml ./docker-compose.yml

echo "----- Unpacking the influx backup -----"

cd ./backups/influxdb/db
sudo tar -x --same-owner -f "$RESTOREDIR/$INFLUXBACKUP"

echo "----- reactivating the stack -----"

cd "$IOTSTACK"
docker-compose up -d

echo "----- reloading the influx databases -----"

docker exec influxdb influxd restore -portable /var/lib/influxdb/backup

echo "----- cleaning up -----"

rm -rf "$RESTOREDIR"

echo "Restore complete!"
